# Docker Compose configuration for development environment
services:

# Third party tools
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "15672:15672"
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server"]

    restart: unless-stopped

# Databases
  payments-db:
    image: postgres:15
    container_name: payments-db
    env_file:
      - payments-db/.env
    volumes:
      - ./payments-db/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments"]
      interval: 5s
      timeout: 5s
      retries: 5
  providers-db:
    image: postgres:15
    container_name: providers-db
    env_file:
      - providers-db/.env
    volumes:
      - ./providers-db/init-db:/docker-entrypoint-initdb.d       
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U providers"]
      interval: 5s
      timeout: 5s
      retries: 5
  merchants-db:
    image: postgres:15
    container_name: merchants-db
    env_file:
      - merchants-db/.env
    volumes:
      - ./merchants-db/init-db:/docker-entrypoint-initdb.d      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U merchants"]
      interval: 5s
      timeout: 5s
      retries: 5
  payments-logs-db:
    image: postgres:15
    container_name: payments-logs-db
    env_file:
      - payments-logs-db/.env
    volumes:
      - ./payments-logs-db/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logs"]
      interval: 5s
      timeout: 5s
      retries: 5

# Gateways
  gateway:
      build: ./gateway
      container_name: gateway
      ports:
        - "8080:80"
      depends_on:
        payments:
          condition: service_started
  saas-gateway:
    image: nginx:alpine
    container_name: saas-gateway
    volumes:
      - ./saas-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./saas-gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - saas-laravel
  gateway-verification:
    build:
      context: ./gateway-verification
    container_name: gateway-verification
    env_file:
      - gateway-verification/.env
    volumes:
      - ./gateway-verification/app:/app
      - /app/node_modules
    depends_on:
      - payments

# SaaS platform
  saas-laravel:
    build: ./saas-laravel
    container_name: saas-laravel
    volumes:
      - ./saas-laravel/app:/var/www
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      payments-db:
        condition: service_healthy

# Service
  payments:
    build: ./payments
    container_name: payments
    env_file: payments/.env
    volumes:
      - ./payments:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      payments-db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
  providers:
    build: ./providers
    container_name: providers
    env_file:
      - providers-db/.env
    volumes:
      - ./providers:/app
    ports:
      - "8002:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
  merchants:
    build: ./merchants
    container_name: merchants
    env_file:
      - merchants/.env
    volumes:
      - ./merchants:/app
    ports:
      - "8001:8000"
    depends_on:
      merchants-db:
        condition: service_healthy
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
  webhook:
    build: ./webhook
    container_name: webhook
    env_file: webhook/.env
    volumes:
      - ./webhook:/app
    depends_on:
      payments-logs-db:
        condition: service_healthy
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

# Workers
  payments-consumer:
    build: ./payments
    container_name: payments-consumer
    env_file: payments/.env
    volumes:
      - ./payments:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      payments-db:
        condition: service_healthy
    #command: >
    #  watchfiles --filter python
    #  "python -u -m app.workers.payments_consumer"
    #  /app
    
    restart: unless-stopped
    
  payments-producer:
    build: ./payments
    container_name: payments-producer
    env_file: payments/.env
    volumes:
      - ./payments:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      payments-db:
        condition: service_healthy
#    command: >
#      watchfiles --filter python
#      "python -u -m app.workers.payments_producer"
#      /app
    restart: unless-stopped
    