services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - payments

  payments:
    build: ./payments
    container_name: payments
    env_file: payments/.env.payments
    volumes:
      - ./payments:/app
    depends_on:
      - rabbitmq
    command: 
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/app
      --reload-dir /app/seeders

  payments-db:
    image: postgres:15
    container_name: payments-db
    env_file: 
      - payments/.env.payments-db
    volumes:
      - payments_pgdata:/var/lib/postgresql/data

  provider:
    build: ./providers
    container_name: provider
    env_file: 
      - providers/.env.providers
    volumes:
      - ./providers:/app
    ports:
      - "9000:8000"
    command: 
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/app
      
  providers-db:
    image: postgres:15
    container_name: providers-db
    env_file:
      - providers/.env.providers-db
    volumes:
      - providers_pgdata:/var/lib/postgresql/data

  merchants:
    build: ./merchants
    container_name: merchants
    env_file: 
      - merchants/.env.merchants
    depends_on:
      - merchants-db
    ports:
      - "8001:8000"
    command:
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/app
      --reload-dir /app/seeders
    volumes:
      - ./merchants:/app

  merchants-db:
    image: postgres:15
    container_name: merchants-db
    env_file: 
      - merchants/.env.merchants-db
    volumes:
      - merchants_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  merchants_pgdata:
  providers_pgdata:
  payments_pgdata: