services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - payments

  payments:
    build: ./payments
    container_name: payments
    env_file: .env.payments
    volumes:
      - ./payments:/app

  payments-db:
    image: postgres:15
    container_name: payments-db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    volumes:
      - pgdata:/var/lib/postgresql/data

  provider:
    build: ./providers
    container_name: provider
    env_file: .env.providers
    ports:
      - "9000:8000"

  merchants:
    build: ./merchants
    container_name: merchants
    env_file: .env.merchants
    depends_on:
      - merchants-db
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://merchants:merchants@merchants-db:5432/merchants
      PAYMENTS_GATEWAY_URL: http://gateway:80
    volumes:
      - ./merchants:/app

  merchants-db:
    image: postgres:15
    container_name: merchants-db
    environment:
      POSTGRES_DB: merchants
      POSTGRES_USER: merchants
      POSTGRES_PASSWORD: merchants
    volumes:
      - merchants_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  providers-db:
    image: postgres:15
    container_name: providers-db
    environment:
      POSTGRES_DB: providers
      POSTGRES_USER: providers
      POSTGRES_PASSWORD: providers
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  merchants_pgdata:
