# Docker Compose configuration for RabbitMQ, Redis, and PostgreSQL databases
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "15672:15672"

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server"]

    restart: unless-stopped

  payments-db:
    image: postgres:15
    container_name: payments-db
    env_file:
      - payments/.env.payments-db
    volumes:
      - ./payments-db/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments"]
      interval: 5s
      timeout: 5s
      retries: 5

  providers-db:
    image: postgres:15
    container_name: providers-db
    env_file:
      - providers/.env.providers-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U providers"]
      interval: 5s
      timeout: 5s
      retries: 5

  merchants-db:
    image: postgres:15
    container_name: merchants-db
    env_file:
      - merchants/.env.merchants-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U merchants"]
      interval: 5s
      timeout: 5s
      retries: 5

