services:

  saas-gateway:
    image: nginx:alpine
    container_name: saas-gateway
    env_file: 
      - gateway/.env.gateway
    volumes:
      - ./saas-laravel:/var/www/html
      - ./saas-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./saas-gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - saas-laravel

  saas-laravel:
    build: ./saas-laravel
    container_name: saas-laravel
    volumes:
      - ./saas-laravel/app:/var/www
    depends_on:
      - payments-db

  gateway:
    build: ./gateway
    container_name: gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/api-verification:/api-verification
    env_file:
      - gateway/.env.gateway
    ports:
      - "8080:80"
    depends_on:
      - payments
    command: >
      sh -c "
      redis-server --daemonize yes &&
      npm run dev &
      nginx -g 'daemon off;'
      "

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"

  payments:
    build: ./payments
    container_name: payments
    env_file: payments/.env.payments
    volumes:
      - ./payments:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      payments-db:
        condition: service_started
    command: 
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/app
      --reload-dir /app/seeders

  payments-worker:
    build: ./payments
    container_name: payments-worker
    command: python -m app.workers.payment_events
    depends_on:
      - rabbitmq
      - payments

  payments-db:
    image: postgres:15
    container_name: payments-db
    env_file: 
      - payments/.env.payments-db
    volumes:
      - payments_pgdata:/var/lib/postgresql/data

  provider:
    build: ./providers
    container_name: provider
    env_file: 
      - providers/.env.providers
    volumes:
      - ./providers:/app
    ports:
      - "9000:8000"
    command: 
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/app
      
  providers-db:
    image: postgres:15
    container_name: providers-db
    env_file:
      - providers/.env.providers-db
    volumes:
      - providers_pgdata:/var/lib/postgresql/data

  merchants:
    build: ./merchants
    container_name: merchants
    env_file: 
      - merchants/.env.merchants
    depends_on:
      - merchants-db
    ports:
      - "8001:8000"
    command:
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/app
      --reload-dir /app/seeders
    volumes:
      - ./merchants:/app

  merchants-db:
    image: postgres:15
    container_name: merchants-db
    env_file: 
      - merchants/.env.merchants-db
    volumes:
      - merchants_pgdata:/var/lib/postgresql/data

volumes:
  merchants_pgdata:
  providers_pgdata:
  payments_pgdata:
