# Docker Compose configuration for development environment
services:
  saas-gateway:
    image: nginx:alpine
    container_name: saas-gateway
    volumes:
      - ./saas-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./saas-gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - saas-laravel

  saas-laravel:
    build: ./saas-laravel
    container_name: saas-laravel
    volumes:
      - ./saas-laravel/app:/var/www
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      payments-db:
        condition: service_healthy

  gateway:
    build: ./gateway
    container_name: auth-gateway
    env_file:
      - gateway/.env
    volumes:
      - ./gateway:/api-verification
    ports:
      - "8080:80"
    depends_on:
      - payments
    command: >
      sh -c "
      npm run dev &
      nginx -g 'daemon off;'
      "

  payments:
    build: ./payments
    container_name: payments
    env_file: payments/.env.payments
    volumes:
      - ./payments:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      payments-db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  payments-worker:
    build: ./payments
    container_name: payments-worker
    env_file: payments/.env.payments
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      payments-db:
        condition: service_healthy
    command: python -m app.workers.payment_events

  gateway-worker:
    build: ./gateway-worker
    container_name: gateway-worker
    command: node index.js
    env_file: ./gateway-worker/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      payments-db:
        condition: service_healthy
      redis:
        condition: service_started

  provider:
    build: ./providers
    container_name: provider
    env_file:
      - providers/.env.providers
    volumes:
      - ./providers:/app
    ports:
      - "9000:8000"
    command: >
      uvicorn app.main:app
      --reload

  merchants:
    build: ./merchants
    container_name: merchants
    env_file:
      - merchants/.env.merchants
    volumes:
      - ./merchants:/app
    ports:
      - "8001:8000"
    depends_on:
      merchants-db:
        condition: service_healthy
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

